name: ARM Weekly Python Scraper

on:
  workflow_dispatch:
  schedule:
    - cron: "0 7 * * 4"  # Run every Thursday at 7 AM (UTC)

jobs:
  build:
    runs-on: chancepi

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Run Python Script
        run: |
          python3 scripts/metroAndFoodBasics.py
