name: Weekly Python Scraper

on:
  workflow_dispatch:
  schedule:
    - cron: "0 7 * * 4"  # Run every Thursday at 7 AM (UTC)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.2'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
        
      - name: Run Python Script
        run: |
          python scripts/metroAndFoodBasics.py
