name: ARM Weekly Python Scraper

on:
  workflow_dispatch:
  schedule:
    - cron: "0 7 * * 4"  # Run every Thursday at 7 AM (UTC)

jobs:
  build:
    runs-on: chancepi

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set up Python
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/arm64
          push: false

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests bs4
        
      - name: Run Python Script
        run: |
          python scripts/metroAndFoodBasics.py
